project:
  type: website

website:
  title: "Team Crane!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    math:
      method: mathjax
      options:
        autoNumber: "AMS"
      citations: true
    link-external-icon: true
    code-line-numbers: true




